import { test, expect, watchErrors, expectAccessible } from './helpers.mjs';

test('card faces, shared base, grouping and clipboard are editable', async ({ page, t }) => {
  const errors = watchErrors(page);
  await page.goto('/index.html?demo=turing88');
  await expect(page.locator('#theme-name')).toHaveValue('Demo');
  const detail = page.locator('#inspector');
  const add = async widget => {
    await page.locator('#tab-widgets').click();
    await page.getByRole('button', { name: t('library.addWidget', { name: t(`widget.${widget}`) }), exact: true }).click();
  };
  await add('card');
  const cardName = await detail.getByLabel(t('inspector.name'), { exact: true }).inputValue();
  await detail.getByLabel(t('card.faceTitle'), { exact: true }).fill('Metrics');
  await detail.getByLabel(t('card.faceTitle'), { exact: true }).press('Tab');
  await add('text');
  await expect(detail.getByRole('combobox', { name: t('card.face'), exact: true })).toHaveValue('0');
  await detail.getByRole('combobox', { name: t('card.face'), exact: true }).selectOption('');
  const selectCard = async () => {
    await page.locator('#tab-layers').click();
    await page.locator('.layer-name').filter({ hasText: cardName }).first().click();
  };
  await selectCard();
  await detail.getByRole('button', { name: t('card.addFace'), exact: true }).click();
  await expect(detail.getByRole('combobox', { name: t('card.activeFace'), exact: true })).toHaveValue('1');
  await add('ring');
  await add('ring');
  await expect(detail.getByRole('combobox', { name: t('card.face'), exact: true })).toHaveValue('1');
  await page.locator('#tab-layers').click();
  const tree = page.locator('.layer-card').filter({ has: page.locator('.layer-name').filter({ hasText: cardName }) }).first();
  await expect(tree.locator('.layer-group')).toHaveCount(3);
  await expect(tree.locator('[data-face="base"] .layer-row')).toHaveCount(1);
  await expect(tree.locator('[data-face="0"] .layer-row')).toHaveCount(0);
  await expect(tree.locator('[data-face="1"] .layer-row')).toHaveCount(2);
  const faceRows = tree.locator('[data-face="1"] .layer-row');
  const rowIds = () => faceRows.evaluateAll(rows => rows.map(row => row.dataset.elementId));
  const originalOrder = await rowIds();
  await faceRows.last().getByRole('button', { name: t('layers.up'), exact: true }).click();
  expect(await rowIds()).toEqual([...originalOrder].reverse());
  await expect(tree.locator('[data-face="base"] .layer-row')).toHaveCount(1);
  await page.locator('#undo').click();
  expect(await rowIds()).toEqual(originalOrder);
  await tree.getByRole('button', { name: 'Metrics', exact: true }).click();
  await expect(detail.getByRole('combobox', { name: t('card.activeFace'), exact: true })).toHaveValue('0');
  await expect(tree.locator('[data-face="0"]')).toHaveClass(/active-face/);
  await tree.locator('[data-face="1"] .layer-name').first().click();
  await expect(detail.getByRole('combobox', { name: t('card.face'), exact: true })).toHaveValue('1');
  await expect(tree.locator('[data-face="1"]')).toHaveClass(/active-face/);
  await selectCard();
  await detail.getByRole('checkbox', { name: t('card.autoRotate'), exact: true }).check();
  await expect(detail.getByRole('spinbutton', { name: t('card.rotationSeconds'), exact: true })).toHaveValue('10');
  await detail.getByRole('spinbutton', { name: t('card.rotationSeconds'), exact: true }).fill('5');
  await detail.getByRole('spinbutton', { name: t('card.rotationSeconds'), exact: true }).press('Tab');
  await expect(detail).toContainText(t('card.rotationHelp'));
  await page.screenshot({ path: test.info().outputPath('card-timer.png') });
  await detail.getByRole('checkbox', { name: t('card.autoRotate'), exact: true }).uncheck();
  await expect(detail.getByRole('spinbutton', { name: t('card.rotationSeconds'), exact: true })).toHaveCount(0);
  await detail.getByRole('button', { name: t('card.duplicateFace'), exact: true }).click();
  await expect(detail.getByRole('combobox', { name: t('card.activeFace'), exact: true })).toHaveValue('2');
  await detail.getByRole('button', { name: t('card.previous'), exact: true }).click();
  await expect(detail.getByRole('combobox', { name: t('card.activeFace'), exact: true })).toHaveValue('1');
  await page.locator('#copy').click(); await page.locator('#paste').click();
  await expect(detail).toContainText(t('inspector.multi', { count: 6 }));
  await page.locator('#undo').click();
  await selectCard();
  await detail.getByRole('button', { name: t('card.removeFace'), exact: true }).click();
  await expect(detail.getByRole('combobox', { name: t('card.activeFace'), exact: true }).locator('option')).toHaveCount(2);
  await expectAccessible(page);
  expect(errors).toEqual([]);
  await page.screenshot({ path: test.info().outputPath('card-editor.png') });
});
