import { test, expect, watchErrors, expectAccessible } from './helpers.mjs';

test('stored screen video becomes theme background with loop, windows and linear transparency', async ({ page, t }) => {
  const errors = watchErrors(page);
  await page.goto('/index.html?demo=vendorCard');
  await page.getByRole('tab', { name: t('library.screen'), exact: true }).click();
  await page.getByRole('tab', { name: t('screen.storageTab'), exact: true }).click();
  const card = page.getByRole('region', { name: t('storage.medium.sd'), exact: true });
  const setBackground = card.getByRole('button', { name: t('storage.action.background'), exact: true });
  await expect(setBackground).toBeDisabled();
  await card.getByRole('option').filter({ has: page.getByText('AMD.mp4', { exact: true }) }).click();
  await expect(setBackground).toBeEnabled();
  await setBackground.click();
  const detail = page.locator('#inspector');
  await expect(detail).toContainText('AMD.mp4');
  await expect(detail).toContainText(t('deviceVideo.preview'));
  const loop = detail.getByRole('checkbox', { name: t('deviceVideo.loop'), exact: true });
  await expect(loop).toBeChecked();
  await loop.uncheck();
  await page.locator('#undo').click();
  await expect(loop).toBeChecked();
  await page.getByRole('button', { name: t('library.addWidget', { name: t('widget.shape') }), exact: true }).click();
  const window = detail.getByRole('checkbox', { name: t('shape.videoWindow'), exact: true });
  await window.check();
  const fade = detail.getByRole('combobox', { name: t('fade.mode'), exact: true });
  await fade.selectOption('linear');
  await detail.getByLabel(t('shape.fadeAngle'), { exact: true }).fill('90');
  await detail.getByLabel(t('shape.fadeAngle'), { exact: true }).press('Tab');
  const start = detail.getByRole('slider', { name: new RegExp(t('shape.fadeStart')) });
  await start.fill('80'); await start.dispatchEvent('change');
  await page.locator('#copy').click(); await page.locator('#paste').click();
  await expect(window).toBeChecked();
  await expect(detail.getByLabel(t('shape.fadeAngle'), { exact: true })).toHaveValue('90');
  await expect(start).toHaveValue('80');
  await fade.selectOption('none');
  await page.locator('#undo').click();
  await expect(fade).toHaveValue('linear');
  await expectAccessible(page);
  expect(errors).toEqual([]);
});
