// Builds the Bezel Evo "Pixel" mark (a B on a 5x7 dot matrix) and regenerates
// every Tauri icon from it.
//
//   node scripts/build-icons.mjs
//
// 1. writes the mark to src/icon.svg and src-tauri/icons/icon.svg;
// 2. runs the pinned Tauri CLI (same pin as scripts/windows/package-evo.ps1) for
//    the default set (PNGs, icon.ico, icon.icns), dropping the android/ and ios/
//    folders the app does not ship;
// 3. runs it again with `-p 1024 -p 64` for the extras: icon-1024.png and the
//    64 px tray icon (tray.png, also installed as 64x64.png on Linux).
//
// The mark itself is a pure function so tests can check the committed SVGs.

import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const TAURI_CLI = '@tauri-apps/cli@2.12.1';

/** The palette of the mark. The accent is the literal value of `--accent`. */
export const PALETTE = Object.freeze({
  tile: '#181B1F',
  rim: '#2C3238',
  dim: '#22272C',
  lit: '#F2EDE6',
  accent: '#FF9248',
  live: '#34D399',
});

/** The letter B, 5 columns by 7 rows. */
const B = ['11110', '10001', '10001', '11110', '10001', '10001', '11110'];
/** Cells of the B lit in the accent colour: the base, like a level. */
const ACC = ['00000', '00000', '00000', '00000', '00001', '00001', '11110'];
/** The top-right cell is the live-status pixel. */
const LIVE = { row: 0, col: 4 };

const CELL = 24;
const GAP = 4;
const RADIUS = 5;
const X0 = 60;
const Y0 = 32;

function roundedSquare(x, y, size, r) {
  const side = size - 2 * r;
  return (
    `M${x + r} ${y}h${side}a${r} ${r} 0 0 1 ${r} ${r}v${side}` +
    `a${r} ${r} 0 0 1 -${r} ${r}h-${side}a${r} ${r} 0 0 1 -${r} -${r}` +
    `v-${side}a${r} ${r} 0 0 1 ${r} -${r}z`
  );
}

/** Splits the 35 cells into the four layers of the mark, as path data. */
export function matrixPaths() {
  const out = { dim: '', lit: '', acc: '', live: '' };
  B.forEach((row, ri) => {
    for (let ci = 0; ci < 5; ci += 1) {
      const d = roundedSquare(X0 + ci * (CELL + GAP), Y0 + ri * (CELL + GAP), CELL, RADIUS);
      if (ri === LIVE.row && ci === LIVE.col) out.live += d;
      else if (ACC[ri][ci] === '1') out.acc += d;
      else if (row[ci] === '1') out.lit += d;
      else out.dim += d;
    }
  });
  return out;
}

/** The full 256x256 app icon SVG. */
export function pixelMarkSvg() {
  const p = matrixPaths();
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256">',
    '  <!-- Bezel Evo "Pixel" mark: a B on a 5x7 dot matrix. Generated by apps/bezel-studio/scripts/build-icons.mjs; do not edit by hand. -->',
    `  <rect width="256" height="256" rx="60" fill="${PALETTE.tile}"/>`,
    `  <rect x="1.5" y="1.5" width="253" height="253" rx="58.5" fill="none" stroke="${PALETTE.rim}" stroke-width="3"/>`,
    `  <path d="${p.dim}" fill="${PALETTE.dim}"/>`,
    `  <path d="${p.lit}" fill="${PALETTE.lit}"/>`,
    `  <path d="${p.acc}" fill="${PALETTE.accent}"/>`,
    `  <path d="${p.live}" fill="${PALETTE.live}"/>`,
    '</svg>',
    '',
  ].join('\n');
}

function tauriIcon(cwd, args) {
  const cli = ['npx', '--yes', TAURI_CLI, 'icon', ...args];
  // npx is a .cmd shim on Windows: run it through cmd.exe instead of `shell: true`.
  const [file, argv] =
    process.platform === 'win32' ? ['cmd.exe', ['/d', '/s', '/c', ...cli]] : [cli[0], cli.slice(1)];
  execFileSync(file, argv, { cwd, stdio: 'inherit' });
}

function main() {
  const app = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const icons = join(app, 'src-tauri', 'icons');
  const svg = pixelMarkSvg();
  writeFileSync(join(app, 'src', 'icon.svg'), svg);
  writeFileSync(join(icons, 'icon.svg'), svg);

  tauriIcon(app, ['src-tauri/icons/icon.svg', '-o', 'src-tauri/icons']);
  rmSync(join(icons, 'android'), { recursive: true, force: true });
  rmSync(join(icons, 'ios'), { recursive: true, force: true });

  const extras = mkdtempSync(join(tmpdir(), 'bezel-icons-'));
  try {
    tauriIcon(app, ['src-tauri/icons/icon.svg', '-o', extras, '-p', '1024', '-p', '64']);
    copyFileSync(join(extras, '1024x1024.png'), join(icons, 'icon-1024.png'));
    copyFileSync(join(extras, '64x64.png'), join(icons, '64x64.png'));
    copyFileSync(join(extras, '64x64.png'), join(icons, 'tray.png'));
  } finally {
    rmSync(extras, { recursive: true, force: true });
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main();
}
